# Generated by Django 4.1.7 on 2023-02-22 01:07

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                validators=[myapp.models.validate_image],
            ),
        ),
    ]
